# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Test installation of EESSI test suite with 'pip install'
on: [push, pull_request, workflow_dispatch]
permissions: read-all
jobs:
  test_pip_install:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
        - name: Check out software-layer repository
          uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
          with:
            persist-credentials: false

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install setuptools
          run: |
            if [[ "${{ matrix.python-version }}" == "3.6" ]]; then
              python -m pip install --user setuptools==39.2.0
            fi

        - name: Install ReFrame
          run: |
            pip install --user ReFrame-HPC

        - name: Install EESSI test suite with 'pip install'
          run: |
            # install from source distribution tarball, to test release as published on PyPI
            rm -rf dist
            python setup.py sdist
            ls dist

            python -m pip install --user dist/eessi*.tar.gz
            find $HOME/.local

            python -c 'import eessi.testsuite.utils'
            python -c 'import eessi.testsuite.tests.apps'
